Web/Controllers/AnswersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using UrTask.Application.DTOs.AnswersDto;
using UrTask.Application.IUC;

namespace Web.Controllers
{
    public class AnswersController : Controller
    {
        private readonly IAnswerUc _usecase;

        public AnswersController(IAnswerUc usecase)
        {
            _usecase = usecase;
        }
      

        public IActionResult AddAnswer(int id,bool isSuccess = false)
        {
            ViewBag.isSuccess = isSuccess;
            ViewBag.message = "تمت الارسال بنجاح";
            ViewBag.alertType = "alert alert-primary";
            var entity = new AnswerAddDto() { TaskId = id };
            return View(entity);
        }
        [HttpPost]
        public IActionResult AddAnswer(AnswerAddDto answer)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    _usecase.Add(answer);
                    return RedirectToAction(nameof(AddAnswer), new {id= answer.TaskId, isSuccess = true });
                }
                catch (Exception e)
                {

                }
                //return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

Web/Controllers/TasksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UrTask.Application.DTOs.TaskDto;
using UrTask.Application.IUC;
using Web.Hubs;
using Web.Shared;

namespace Web.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITaskUC _usecase;
        IList<TaskGetDto> lstData;
        private readonly IHubContext<TaskHub> _hubContext;

        public TasksController(ITaskUC usecase,  IHubContext<TaskHub> hubContext)
        {
            _usecase = usecase;
            _hubContext = hubContext;
        }
        public IActionResult Index()
        {
            lstData = _usecase.GetAll() ;
            List<TaskGetDto> data = lstData as List<TaskGetDto>;
            data.Reverse();
            return View(data);
        }

        public IActionResult AddTask(bool isSuccess = false)
        {
            ViewBag.isSuccess = isSuccess;
            ViewBag.message = "تمت الارسال بنجاح";
            ViewBag.alertType = "alert alert-primary";
            return View();
        }
        
        public IActionResult UpdatePrice(int id ,string  price)
        {
            try
            {
                _usecase.UpdatePrice(id, Convert.ToDouble(price));
                return RedirectToAction("Index");

            }catch(Exception e)
            {

            }
            return RedirectToAction("Index");

        }
        [HttpPost]
        public async Task<IActionResult> AddTask(TaskAddDto task)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    _usecase.Add(task);
                    await _hubContext.Clients.All.SendAsync("NewTaskRecived", "تمت اضافة مهمة جديدة");
                    return RedirectToAction(nameof(AddTask), new { isSuccess = true });
                }catch(Exception e)
                {

                }
                //return RedirectToAction(nameof(Index));
            }
            return View();
        }


        
        public IActionResult setStatues(int id, int statues)
        {
            _usecase.SetStatues(id, statues);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult TaskDetails(int id)
        {
            return View(_usecase.GetById(id));
        }

        public IActionResult StudentTasks()
        {
            int userId = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "UserId").Value);

            lstData = _usecase.GetAllByUserId(userId);
            List<TaskGetDto> data = lstData as List<TaskGetDto>;
            data.Reverse();
            return RedirectToAction("Student","Home",new { tasks = data });
        }

        
    }
}

Web/Views/Answers/AddAnswer.cshtml
@model AnswerAddDto

@{
    Layout = "_sidebar";
    

}
<main id="main" dir="ltr" class="main">

    <div class="wrapper wrapper-content" dir="rtl">
        @if (ViewBag.isSuccess == true)
        {
        <div class="@ViewBag.alertType" role="alert">
            @*saved done <a asp-controller="book" asp-action="GetBookByI" asp-route-id="@ViewBag.bookId" class="alert-link">go to details</a>. Give it a click if you like.*@
            @ViewBag.message
        </div>
        }
        <div class="container">
            <h3>  اضافة اجابة </h3>-

        </div>
        <form method="post" enctype="multipart/form-data" asp-action="AddAnswer" asp-controller="Answers">
            <div class="form-group">
                <label style="position:center"> المحتوى</label>
                <textarea class="form-control" asp-for="Notes" style="height:40px"></textarea>
                <span class="text-danger" asp-validation-for="Notes"></span>
            </div>
            <input type="text"  asp-for="TaskId"hidden />
            <div class="form-group">
                <span>المرفقات:</span>
                <input type="file" multiple asp-for="Files" class="form-control" />
            </div>


            <div class="form-group">
                <button type="submit" value="add task" class="btn btn-primary" id="sendButton"> اضافةاجابة</button>
                <button asp-action="Index" asp-controller="Tasks" value="all tasks" class="btn btn-primary"> كافة المهام</button>
                <button asp-action="TaskDetails" asp-controller="Tasks" asp-route-id="@Model.TaskId" class="btn btn-primary"> تفاصيل المهه</button>
            </div>
        </form>
    </div>


</main>