Web/Controllers/MajorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using UrTask.Application.DTOs.MajorDto;
using UrTask.Application.IUC;

namespace Web.Controllers
{
    public class MajorsController : Controller
    {
        //private readonly IUnitOfWork UnitOfWork;
        private readonly IMajor usecase;
        IList<MajorGetDto> lstData;
        public MajorsController(IMajor usecase)
        {
            
            this.usecase = usecase;
        }
        public IActionResult Index(bool isSuccess = false)
        {
            ViewBag.message = "تم الحذف بنجاح";
            ViewBag.isSuccess = isSuccess;
            ViewBag.alertType = "alert alert-danger";

            lstData = usecase.GetAll();

            return View(lstData);
        }
        public IActionResult AddMajor(bool isSuccess = false)
        {
            
            ViewBag.isSuccess = isSuccess;
            ViewBag.message = "تمت الاضافة بنجاح";
            ViewBag.alertType = "alert alert-primary";
            return View();
        }
        [HttpPost]
        public IActionResult AddMajor(MajorAddDto major)
        {
           
            if (ModelState.IsValid)
            {

                try
                {
                    usecase.Add(major);

                    return RedirectToAction(nameof(AddMajor), new { isSuccess = true });
                }catch(Exception e)
                {

                }

                //return RedirectToAction(nameof(Index)); 
            }
           

            return View();
        }
        public IActionResult DeleteMajor(int id)
        {
            try
            {
                usecase.Delete(id);
                return RedirectToAction(nameof(Index), new { isSuccess = true });
            }catch(Exception e)
            {

            }
            return RedirectToAction(nameof(Index), new { isSuccess = false });
        }

        public IActionResult UpdateMajor(int id)
        {
            return View(usecase.GetByIdUpdate(id));
        }
        [HttpPost]
        public IActionResult UpdateMajor(int id, MajorUpdateDto major )
        {
           
            if (ModelState.IsValid)
            {
                try
                {
                    usecase.Edit(id, major);
                    return RedirectToAction(nameof(Index));
                }catch(Exception e)
                {

                }
            }
            return View();

        }
    }
}

Web/Views/Majors/AddMajor.cshtml
@model MajorAddDto


@{
    Layout = "_sidebar";
}

<main id="main" dir="ltr" class="main">

    <div class="wrapper wrapper-content" dir="rtl">
        @if (ViewBag.isSuccess  == true)
        {
            <div class="@ViewBag.alertType" role="alert">
                @*saved done <a asp-controller="book" asp-action="GetBookByI" asp-route-id="@ViewBag.bookId" class="alert-link">go to details</a>. Give it a click if you like.*@
                @ViewBag.message
            </div>
        }
        <div class="container">
            <h3>اضافة تخصص جديد</h3>

        </div>
        <form method="post" asp-action="AddMajor" asp-controller="Majors">

            <div class="form-group">
                <label>اسم التخصص</label>
                <input type="text" class="form-control" asp-for="Name" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="form-group">
                <label>ملاحظات</label>
                <input type="text" class="form-control" asp-for="Notes" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>تاريخ</label>
                <input type="text" class="form-control" asp-for="EnterdDate" hidden value="@DateTime.Now" />
                <span class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" value="add major" class="btn btn-primary"> اضافة</button>
                <button asp-action="Index" value="all majors" class="btn btn-primary"> كافة التخصصات</button>
            </div>
        </form>
    </div>

        
    </main>

Web/Views/Majors/Index.cshtml
@model IEnumerable<MajorGetDto>
@{
    Layout = "_sidebar";
    //ViewBag.isSusse = false;

}

<main id="main" dir="ltr" class="main">

    <div class="wrapper wrapper-content" dir="rtl">
        @if (ViewBag.isSuccess  == true)
        {
            <div class="@ViewBag.alertType" role="alert">
                @*saved done <a asp-controller="book" asp-action="GetBookByI" asp-route-id="@ViewBag.bookId" class="alert-link">go to details</a>. Give it a click if you like.*@
              @ViewBag.message
            </div>
        }
        <div class="col-12">
            <br>
            <h3 class="titulo-tabla">قائمة التخصصات </h3>
            <hr>

            <table id="dtHorizontalVerticalExample" class="table table-striped table-bordered table-sm " cellspacing="0"
                   width="100%">
                <thead>
                    <tr>
                        <th>م</th>
                        <th>اسم التخصص</th>
                        <th>تاريخ الادخال</th>
                        <th>ملاحظات</th>
                        <th>الحدث</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var majorItem in Model)
                    {
                        <tr>
                            <td>@majorItem.Id</td>
                            <td>@majorItem.Name</td>
                            <td>@majorItem.EnterdDate</td>
                            <td>@majorItem.Notes</td>
                            <td>
                                <a class="bi bi-trash" asp-action="DeleteMajor" asp-route-id="@majorItem.Id"></a>
                                <a class="bi bi-pencil-square" asp-action="UpdateMajor" asp-route-id="@majorItem.Id"></a>
                            </td>


                        </tr>
                    }

                </tbody>
            </table>






        </div>
        <a class="btn btn-success" asp-action="AddMajor" asp-controller="Majors">اضافة تخصص</a>

    </div>
</main>

Web/Views/Majors/UpdateMajor.cshtml
@model MajorUpdateDto


@{
    Layout = "_sidebar";
}
<main id="main" dir="ltr" class="main">

    <div class="wrapper wrapper-content" dir="rtl">
        <div class="container">
            <h3>تعديل تخصص جديد</h3>

        </div>
        <form method="post" asp-action="UpdateMajor" asp-controller="Majors">

            <div class="form-group">
                <label>اسم التخصص</label>
                <input type="text" class="form-control" asp-for="Name" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="form-group">
                <label>ملاحظات</label>
                <input type="text" class="form-control" asp-for="Notes" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>تاريخ</label>
                <input type="text" class="form-control" asp-for="EnterdDate" hidden value="@DateTime.Now" />
                <span class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" value="update major" class="btn btn-primary"> تعديل</button>
                @*<button type="submit" value="all majors" class="btn btn-primary"> كافة التخصصات</button>*@
            </div>
        </form>
    </div>


</main>